# Generated by Django 4.0.1 on 2023-01-07 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_remove_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_teacher',
            field=models.CharField(choices=[('Teacher', True), ('Student', False)], default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='is_teacher',
            field=models.CharField(choices=[('Teacher', True), ('Student', False)], default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
