# Generated by Django 4.0.1 on 2023-01-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
