# Generated by Django 4.0.1 on 2023-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
