# Generated by Django 4.0.1 on 2023-05-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendance_date_remove_attendance_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attentiveness',
            field=models.IntegerField(default=83),
            preserve_default=False,
        ),
    ]
